version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iquit
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - iquit_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - iquit_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/iquit
      JWT_SECRET_KEY: super-secret-key
      DEBUG_FAKE_DATA: 'false'
      FLASK_ENV: production
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      - db
      - rabbitmq
    networks:
      - iquit_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.background_tasks.celery worker --loglevel=info
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/iquit
      JWT_SECRET_KEY: super-secret-key
      DEBUG_FAKE_DATA: 'false'
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      CELERY_RESULT_BACKEND: rpc://
    depends_on:
      - backend
      - rabbitmq
    networks:
      - iquit_net

volumes:
  db_data:

networks:
  iquit_net:
    driver: bridge
